# NumPy Basics: Arrays and Vectorized Computation

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
#Now let’s multiply each sequence by 2:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 31.2 ms
Wall time: 36 ms
CPU times: total: 1.73 s
Wall time: 1.8 s


## The NumPy ndarray: A Multidimensional Array Object

In [4]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.78038511,  0.55117232, -0.32420316],
       [-0.20079279, -1.29028968,  1.50854242]])

In [7]:
data * 10

array([[ -7.80385113,   5.51172319,  -3.2420316 ],
       [ -2.00792788, -12.90289676,  15.08542416]])

In [8]:
data + data

array([[-1.56077023,  1.10234464, -0.64840632],
       [-0.40158558, -2.58057935,  3.01708483]])

In [9]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
arr1

[6.  7.5 8.  0.  1. ]


array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
arr2

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2, 3, 2))

array([[[3.81749955e-316, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.16709769e-312, 1.27890447e+165]],

       [[4.89186200e-033, 2.77437475e+180],
        [6.40557436e+170, 1.69136054e-052],
        [1.93583716e+184, 5.24243456e+174]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [24]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [25]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [26]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [27]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [28]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [29]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [30]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [33]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([  42008794,          0, 2002804768, 1702127986, 1701601889,
       1818314301, 1616930163,  544175136], dtype=uint32)

### Arithmetic with NumPy Arrays

In [34]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [41]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[5:8]

array([5, 6, 7])

In [45]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [46]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [47]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [48]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [78]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [79]:
arr2d[0][2]

3

In [80]:
arr2d[0, 2]

3

In multidimensional arrays, if you omit later indices, the returned object will be a
lower dimensional ndarray consisting of all the data along the higher dimensions. So
in the 2 × 2 × 3 array `arr3d`:

In [81]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr3d[1, 0]

array([7, 8, 9])

In [86]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [87]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [88]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [89]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [90]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [93]:
arr2d[1, :2]

array([4, 5])

In [102]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [97]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [98]:
lower_dim_slice.shape

(2,)

In [99]:
arr2d[:2, 2]

array([3, 6])

In [100]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [103]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [106]:
#data = np.random.randn(7, 4)
#data

array([[-0.25396549, -0.05218649, -0.02849455,  0.78895016],
       [ 0.3220724 ,  0.03618834,  1.37312144,  0.36613667],
       [-2.73643498, -0.14169319,  0.25035704, -0.33360951],
       [-0.48610519, -0.10919558, -0.50246133, -0.54660148],
       [-0.63742383,  0.82373399,  0.04858323, -1.35361339],
       [-1.28974398, -1.14976796,  2.56686571, -2.24675092],
       [ 0.98896952,  0.009411  , -1.13253596, -0.86250679]])

In [110]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [111]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                  [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [112]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [113]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [114]:
data[names == "Bob", 2:]

array([], shape=(2, 0), dtype=int32)

In [119]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [117]:
data[names == "Bob", 1]

array([7, 0])

In [120]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [121]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [122]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [125]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [126]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [127]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [130]:
data[data < 0] = 0
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [131]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing

In [132]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [133]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [134]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [135]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [137]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [138]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [139]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [140]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [147]:
arr = arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [148]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [149]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [150]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [151]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [152]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [153]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [154]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [155]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [162]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [164]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [165]:
x = np.random.randn(8)
x

array([-1.5619348 ,  0.21387893, -0.28947876, -0.41379314, -2.59195757,
        0.2251082 , -0.8265012 , -0.18327149])

In [166]:
y = np.random.randn(8)
y

array([-0.31160089,  1.52404665,  0.14335869,  0.93155042, -1.51430835,
        2.30801795, -0.74627091, -0.16745558])

In [167]:
np.maximum(x, y)

array([-0.31160089,  1.52404665,  0.14335869,  0.93155042, -1.51430835,
        2.30801795, -0.74627091, -0.16745558])

In [168]:
arr = np.random.randn(7) * 5
arr

array([-0.51751156, -6.12307142,  4.6132319 ,  7.59886723,  1.56672458,
        3.74172792, -8.08970677])

In [169]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.51751156, -0.12307142,  0.6132319 ,  0.59886723,  0.56672458,
        0.74172792, -0.08970677])

In [186]:
whole_part

array([-0., -6.,  4.,  7.,  1.,  3., -8.])

Ufuncs accept an optional out argument that allows them to assign their results into
an existing array rather than create a new one:

In [187]:
arr

array([       nan,        nan, 1.4655523 , 1.66030247, 1.11878894,
       1.39081079,        nan])

In [188]:
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [189]:
np.add(arr, 1)

array([       nan,        nan, 2.4655523 , 2.66030247, 2.11878894,
       2.39081079,        nan])

In [190]:
np.add(arr, 1, out=out)

array([       nan,        nan, 2.4655523 , 2.66030247, 2.11878894,
       2.39081079,        nan])

In [191]:
out

array([       nan,        nan, 2.4655523 , 2.66030247, 2.11878894,
       2.39081079,        nan])

In [ ]:
np.sqrt(arr)
np.sqrt(arr, arr)
arr

## Array-Oriented Programming with Arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = np.random.randn(6)
arr
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and Other Set Logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Pseudorandom Number Generation

In [156]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.2548273 ,  1.70876624,  2.29671571,  0.33802027],
       [ 0.41589386,  2.26136793, -0.87107669, -2.93757186],
       [-0.65642054, -0.70824757, -0.09010205,  1.43717194],
       [-1.00233488, -0.18524908,  0.41021246, -0.69613187]])

In [158]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

2.87 s ± 582 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
97.1 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

In [160]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
type(rng)

numpy.random._generator.Generator

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating Many Random Walks at Once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

## Conclusion